package com.remoticom.streetlighting.services.bluetooth.gatt.bdc

import android.bluetooth.BluetoothGattCharacteristic

// prefix - device type - service - characteristic - mac address
const val BDC_BLUETOOTH_SERVICE_MASK = "FFFFFFFF-FFFF-FFFF-0000-000000000000"

const val BDC_BLUETOOTH_SERVICE_GENERAL_MASK =
  "A55D1C55-0088-0000-0000-000000000000"
const val BDC_BLUETOOTH_SERVICE_DIM_MASK = "A55D1C55-0088-0001-0000-000000000000"

//const val BLUETOOTH_SERVICE_LUX_MASK = "A55D1C55-0088-0002-0000-000000000000"
const val BDC_BLUETOOTH_SERVICE_DALI_MASK = "A55D1C55-0088-0003-0000-000000000000"

const val BDC_BLUETOOTH_SERVICE_TIME_MASK = "A55D1C55-0088-0004-0000-000000000000"

const val BDC_BLUETOOTH_SERVICE_GPS_MASK = "A55D1C55-0088-0005-0000-000000000000"

const val BDC_BLUETOOTH_SERVICE_DIAGNOSTICS_MASK =
  "A55D1C55-0088-0009-0000-000000000000"
const val BDC_BLUETOOTH_SERVICE_SECURITY_MASK = "A55D1C55-0088-000A-0000-000000000000"

const val BDC_BLUETOOTH_CHARACTERISTIC_GENERAL_MODE = 0x0001L
const val BDC_BLUETOOTH_CHARACTERISTIC_GENERAL_NAME = 0x0002L

// DIM
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_PRESET = 0x0001L
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS = 0x0002L
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_NOMINAL_LIGHT_LEVEL = 0x0003L
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_NOMINAL_LIGHT_LEVEL_INDEX_W = 3

const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_COUNT = 5

const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_BYTES_PER_STEP = 6
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_INDEX_HOUR = 0
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_INDEX_MINUTE = 1
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_INDEX_R = 2
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_INDEX_G = 3
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_INDEX_B = 4
const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_STEPS_INDEX_W = 5

const val BDC_BLUETOOTH_CHARACTERISTIC_DIM_PRESET_PLAN_DISABLED = 0 // Enabled is > 0 (# of dim steps)

// LUX
const val BLUETOOTH_CHARACTERISTIC_LUX_DAY = 0x0001L
const val BLUETOOTH_CHARACTERISTIC_LUX_NIGHT = 0x0002L

// DALI
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_CLO = 0x0001L
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_POWER_LEVEL = 0x0002L
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_AVAILABLE_POWER_LEVELS = 0x0003L // Request Powerlevel
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_FIXTURE_NAME = 0x0004L
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_FADE_TIME = 0x0005L

const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_REQUEST = 0x0007L
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_RESPONSE = 0x0008L

const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_1 = 0x01
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_202 = 0xCA
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_203 = 0xCB
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_204 = 0xCC
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_205 = 0xCD
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_206 = 0xCE
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_BANK_207 = 0xCF

const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_BOOL = 0x01
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_INT8 = 0x01
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_INT16 = 0x02
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_UINT8 = 0x01
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_UINT16 = 0x02
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_UINT24 = 0x03
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_UINT32 = 0x04
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_UINT48 = 0x06
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_MEMORY_SIZE_UINT64 = 0x08


const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_AVAILABLE_POWER_LEVELS_COUNT = 7
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_AVAILABLE_POWER_LEVELS_BYTES_PER_LEVEL = 1
const val BDC_BLUETOOTH_CHARACTERISTIC_DALI_AVAILABLE_POWER_LEVELS_LEVEL_FORMAT = BluetoothGattCharacteristic.FORMAT_UINT8


// TIME
const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_TIMEZONE = 0x0001L
const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_UNIX_TIMESTAMP = 0x0002L
const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_MIDNIGHT_OFFSET = 0x0003L

const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_TIMEZONE_INDEX_OFFSET = 0
const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_TIMEZONE_INDEX_DST = 1
const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_TIMEZONE_DST_DISABLED = 0
const val BDC_BLUETOOTH_CHARACTERISTIC_TIME_TIMEZONE_DST_ENABLED = 1

// GPS
const val BDC_BLUETOOTH_CHARACTERISTIC_GPS_POSITION = 0x0001L
const val BDC_BLUETOOTH_CHARACTERISTIC_GPS_POSITION_BYTES_PER_COMPONENT = 4

// DIAGNOSTICS
const val BDC_BLUETOOTH_CHARACTERISTIC_DIAGNOSTICS_STATUS = 0x0001L
const val BDC_BLUETOOTH_CHARACTERISTIC_DIAGNOSTICS_VERSION = 0x0002L
const val BDC_BLUETOOTH_CHARACTERISTIC_DIAGNOSTICS_VERSION_COUNT = 2
const val BDC_BLUETOOTH_CHARACTERISTIC_DIAGNOSTICS_VERSION_BYTES_PER_VERSION = 3

const val BDC_BLUETOOTH_CHARACTERISTIC_DIAGNOSTICS_STATUS_D4I_ERROR = 0x01

// SECURITY
const val BDC_BLUETOOTH_CHARACTERISTIC_SECURITY_PASSWORD = 0x0001L


